project:
  type: website

website:
  title: "Hareesh Kolluru"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: work.qmd
        text: work
      - href: journal.qmd
        text: journal

format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.css
    toc: true



